/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos_h2;

import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import myUtilities.MessageHandler;
import myUtilities.system_utilities.SystemUtilities;
import pos_h2_database.DB_Discount;
import pos_h2_database.Discount;

/**
 *
 * @author KL_Schweizer
 */
public class DiscountDialog extends javax.swing.JDialog {

    final int rowHeight = 30;
    private static final DecimalFormat df = new DecimalFormat("0.00");
    
    DefaultTableModel dtm;
    
    private ArrayList<String> idList = new ArrayList<>();
    private HashMap<String, Discount> discounts = new HashMap<>();
    
    public DiscountDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        createColumns();
        processTable("", 0);
        setupTable();
        setup();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table_discounts = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textField_name = new javax.swing.JTextField();
        textField_value = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        button_add = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textField_amount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        label_value = new javax.swing.JLabel();
        button_delete = new javax.swing.JButton();
        button_update = new javax.swing.JButton();
        button_clear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        label_result = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jScrollPane2.setFocusable(false);

        table_discounts.setFillsViewportHeight(true);
        table_discounts.setFocusable(false);
        table_discounts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_discounts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_discounts.getTableHeader().setResizingAllowed(false);
        table_discounts.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(table_discounts);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Discount Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Discount Value");

        textField_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textField_nameKeyReleased(evt);
            }
        });

        textField_value.setText("0");
        textField_value.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textField_valueFocusLost(evt);
            }
        });
        textField_value.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textField_valueKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("%");

        button_add.setText("Add");
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Sample Amount");

        textField_amount.setText("1000");
        textField_amount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textField_amountFocusLost(evt);
            }
        });
        textField_amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textField_amountKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("x");

        label_value.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_value.setText("0.00%");

        button_delete.setText("Delete");
        button_delete.setEnabled(false);
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        button_update.setText("Update");
        button_update.setEnabled(false);
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });

        button_clear.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        button_clear.setText("CLR");
        button_clear.setFocusable(false);
        button_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clearActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("=");

        label_result.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_result.setText("1000.00");

        label_id.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        label_id.setText("Id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField_name)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textField_value, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_update))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(textField_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_value)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_result))
                            .addComponent(label_id))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(button_clear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textField_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textField_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(label_value)
                            .addComponent(jLabel8)
                            .addComponent(label_result))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_add)
                            .addComponent(button_delete)
                            .addComponent(button_update)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clearActionPerformed
        emptyFields();
    }//GEN-LAST:event_button_clearActionPerformed

    private void textField_amountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_amountKeyReleased
        triggerAmount();
    }//GEN-LAST:event_textField_amountKeyReleased
    
    private void textField_valueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_valueKeyReleased
        triggerValue();
    }//GEN-LAST:event_textField_valueKeyReleased

    private void textField_valueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textField_valueFocusLost
        SystemUtilities su = new SystemUtilities();
        
        if(!su.isANumber(textField_value.getText())){
            textField_value.setText("0");
            triggerValue();
        }
    }//GEN-LAST:event_textField_valueFocusLost

    private void textField_amountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textField_amountFocusLost
        SystemUtilities su = new SystemUtilities();
        
        if(!su.isANumber(textField_amount.getText())){
            textField_amount.setText("1000");
            triggerAmount();
        }
    }//GEN-LAST:event_textField_amountFocusLost

    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        if(textField_name.getText().isBlank() || textField_value.getText().isBlank()){
            new MessageHandler().warning("Fill proper details!");
        }else{
            DB_Discount discountDb = new DB_Discount();
            Discount discount = new Discount();
            discount.setName(textField_name.getText());
            discount.setValue(textField_value.getText());
            discountDb.insertData(discount);
            processTable("", 0);
            emptyFields();
        }
    }//GEN-LAST:event_button_addActionPerformed

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        DB_Discount discountDb = new DB_Discount();
        Discount discount = new Discount();
        discount.setId(label_id.getText().substring(3));
        discountDb.deleteData(discount);
        processTable("", 0);
        emptyFields();
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        if(textField_name.getText().isBlank() || textField_value.getText().isBlank()){
            new MessageHandler().warning("Fill proper details!");
        }else{
            DB_Discount discountDb = new DB_Discount();
            Discount discount = new Discount();
            discount.setId(label_id.getText().substring(3));
            discount.setName(textField_name.getText());
            discount.setValue(textField_value.getText());
            discountDb.updateData(discount);
            processTable("", 0);
            emptyFields();
        }
    }//GEN-LAST:event_button_updateActionPerformed

    private void textField_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_nameKeyReleased
        processTable(textField_name.getText(), 0);
    }//GEN-LAST:event_textField_nameKeyReleased

    private void triggerAmount(){
        SystemUtilities su = new SystemUtilities();

        double result = 0;
        double amount = 0;
        double percentage = 0;
        if(su.isANumber(textField_amount.getText())){
            amount = Double.parseDouble(textField_amount.getText());
            percentage = Double.parseDouble(label_value.getText().substring(0, label_value.getText().length() - 1));
            result = amount - (amount * (percentage / 100));
            df.setRoundingMode(RoundingMode.UP);
            label_result.setText(df.format(result) + "");
        }
    }
    
    private void triggerValue(){
        SystemUtilities su = new SystemUtilities();
        
        if(su.isANumber(textField_value.getText())){
            df.setRoundingMode(RoundingMode.UP);
            double result = Double.parseDouble(textField_value.getText());
            label_value.setText(df.format(result) + "%");
            triggerAmount();
        }
    }
    
    private void createColumns(){
        dtm = new DefaultTableModel(0,0){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        table_discounts.setModel(dtm);
        dtm.addColumn("ID");
        dtm.addColumn("Name");
        dtm.addColumn("Value");
    }
    
    private void setup(){
        //SETUP
        TableColumnModel tcm = table_discounts.getColumnModel();
        table_discounts.removeColumn(tcm.getColumn(0));
    }
    
    private void processTable(String keyword, int col){
        DB_Discount discountDb = new DB_Discount();
        
        dtm.setRowCount(0);
        
        idList = discountDb.getIdList();
        discounts = discountDb.processData(keyword, col);
        
        for(int i = 0; i < discounts.size(); i++){
            String id = idList.get(i);
            String[] rowData = {
                discounts.get(id).getId(),
                discounts.get(id).getName(),
                discounts.get(id).getValue()
            };
            dtm.addRow(rowData);
        }
        table_discounts.setRowHeight(rowHeight);
    }
    
    private void setupTable(){
        table_discounts.addMouseListener(new MouseListener(){
            private boolean onTable = false;
            
            @Override
            public void mouseClicked(MouseEvent e) {
                if(onTable)
                {
                    Point p = e.getPoint();
                    int y = p.y / rowHeight;
                    if(y < dtm.getRowCount())
                        setFields(discounts.get(dtm.getValueAt(y, 0) + ""));
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
                
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                onTable = true;
            }

            @Override
            public void mouseExited(MouseEvent e) {
                onTable = false;
            }
        });
        
        table_discounts.addMouseMotionListener(new MouseMotionListener() {
            @Override
            public void mouseDragged(MouseEvent e) {
                
            }

            @Override
            public void mouseMoved(MouseEvent e) {
                Point p = e.getPoint();
                int y = p.y / rowHeight;
                if(y < dtm.getRowCount())
                    table_discounts.setRowSelectionInterval(0, y);
            }
        });
    }
    
    private void setFields(Discount discount){
        label_id.setText("Id: " + discount.getId());
        
        textField_name.setText(discount.getName());
        textField_value.setText(discount.getValue());
        
        normalMode(false);
    }
    
    private void emptyFields(){
        label_id.setText("Id:");
        textField_name.setText("");
        textField_value.setText("0");
        textField_amount.setText("1000");
        label_value.setText("0.00%");
        label_result.setText("1000.00");
        
        normalMode(true);
    }
    
    private void normalMode(boolean normal){
        button_add.setEnabled(normal);
        button_delete.setEnabled(!normal);
        button_update.setEnabled(!normal);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_clear;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_result;
    private javax.swing.JLabel label_value;
    private javax.swing.JTable table_discounts;
    private javax.swing.JTextField textField_amount;
    private javax.swing.JTextField textField_name;
    private javax.swing.JTextField textField_value;
    // End of variables declaration//GEN-END:variables
}
