/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos_h2;

import java.awt.Frame;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import myUtilities.MessageHandler;
import pos_h2_database.DB_TransferStocks;
import pos_h2_database.StockTransfer;

/**
 *
 * @author KL_Schweizer
 */
public class ViewTransferStockDialog extends javax.swing.JDialog {

    private DefaultTableModel dtm;
    private MainFrame mf;
    private HashMap<String, StockTransfer> stockTransfers;
    private Frame parent;
    
    public ViewTransferStockDialog(java.awt.Frame parent, boolean modal, MainFrame mainFrame) {
        super(parent, modal);
        
        mf = mainFrame;
        this.parent = parent;
        
        initComponents();
        
        createColumns();
        prepareTable();
        setupTable();
    }
    
    private void createColumns(){
        dtm = new DefaultTableModel(0,0){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        table_transfer.setModel(dtm);
        dtm.addColumn("ID");
        dtm.addColumn("Store");
        dtm.addColumn("Date");
    }
    
    private void prepareTable(){
        DB_TransferStocks tsDb = new DB_TransferStocks();
        
        dtm.setRowCount(0);
        
        stockTransfers = tsDb.processData("", 0);
        ArrayList<String> idLists = tsDb.getIdList();
        
        for(int i = idLists.size() - 1; i >= 0; i--){
            String id = idLists.get(i);
            String[] rowData = {
                stockTransfers.get(id).getId(),
                stockTransfers.get(id).getStoreId(),
                stockTransfers.get(id).getDate()
            };
            dtm.addRow(rowData);
        }
        
        if(table_transfer.getRowCount() > 0)
            table_transfer.setRowSelectionInterval(0, 0);
        
        table_transfer.setRowHeight(30);
        label_transferCount.setText(stockTransfers.size() + " transfer/s");
    }
    
    private void setupTable(){
        table_transfer.addMouseListener(new MouseListener() {
            private boolean onTable = false;
            
            @Override
            public void mouseClicked(MouseEvent e) {
                if(onTable)
                {
                    Point p = e.getPoint();
                    int y = p.y / 30;
                    if(y < dtm.getRowCount())
                        displaySelectedId();
                }
            }
            @Override
            public void mousePressed(MouseEvent e) {
            }
            @Override
            public void mouseReleased(MouseEvent e) {
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                onTable = true;
            }
            @Override
            public void mouseExited(MouseEvent e) {
                onTable = false;
            }
        });
        
        table_transfer.addMouseMotionListener(new MouseMotionListener() {
            @Override
            public void mouseDragged(MouseEvent e) {
                
            }

            @Override
            public void mouseMoved(MouseEvent e) {
                Point p = e.getPoint();
                int y = p.y / 30;
                if(y < dtm.getRowCount())
                    table_transfer.setRowSelectionInterval(0, y);
            }
        });
    }
    
    private void displaySelectedId(){
        StockTransfer st = stockTransfers.get(dtm.getValueAt(table_transfer.getSelectedRow(), 0));
        ViewSingleTransferStock viewSingle = new ViewSingleTransferStock(parent, true, st);
        int x = (mf.getWidth() - viewSingle.getWidth()) / 2;
        int y = (mf.getHeight() - viewSingle.getHeight()) / 2;
        viewSingle.setLocation(x,y);
        viewSingle.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_transfer = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        label_transferCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setFocusable(false);

        table_transfer.setFillsViewportHeight(true);
        table_transfer.setFocusable(false);
        table_transfer.setRequestFocusEnabled(false);
        table_transfer.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_transfer.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_transfer.getTableHeader().setResizingAllowed(false);
        table_transfer.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_transfer);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Total Transfer:");

        label_transferCount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_transferCount.setText("0 transfer/s");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_transferCount)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(label_transferCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_transferCount;
    private javax.swing.JTable table_transfer;
    // End of variables declaration//GEN-END:variables
}
